// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCx3zQz6902VRUIB0q21YnoQxahSEAtn5s',
    appId: '1:542902146379:web:7b75169b837a55307344ce',
    messagingSenderId: '542902146379',
    projectId: 'assignment-384aa',
    authDomain: 'assignment-384aa.firebaseapp.com',
    storageBucket: 'assignment-384aa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCD3PL_6fLXCzH8klsW0rNcMXt0jZzUDCE',
    appId: '1:542902146379:android:76a2bda424bf707b7344ce',
    messagingSenderId: '542902146379',
    projectId: 'assignment-384aa',
    storageBucket: 'assignment-384aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf9lfcxjLBiiZAarQpsCbwL080xiWCD-4',
    appId: '1:542902146379:ios:df6e3b834fd1cb9a7344ce',
    messagingSenderId: '542902146379',
    projectId: 'assignment-384aa',
    storageBucket: 'assignment-384aa.appspot.com',
    iosBundleId: 'com.example.assignment12',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf9lfcxjLBiiZAarQpsCbwL080xiWCD-4',
    appId: '1:542902146379:ios:a47aca31f06cbdbc7344ce',
    messagingSenderId: '542902146379',
    projectId: 'assignment-384aa',
    storageBucket: 'assignment-384aa.appspot.com',
    iosBundleId: 'com.example.assignment12.RunnerTests',
  );
}
